version: '3'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: fraud-detection-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fraud-detection
    networks:
      - fraud-detection-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fraud-detection-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/fraud-detection
      - JWT_SECRET=fd789b52c346a91e8f7d2b9a4c5e0183
      - JWT_EXPIRES_IN=30d
      - BATCH_API_URL=http://python-batch:5000
      - RULES_API_URL=http://python-rules:5001
    networks:
      - fraud-detection-network

  # Frontend
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fraud-detection-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
    networks:
      - fraud-detection-network

  # Python Batch API
  python-batch:
    build:
      context: ./python
      dockerfile: Dockerfile.batch
    container_name: fraud-detection-python-batch
    ports:
      - "5001:5000"
    networks:
      - fraud-detection-network

  # Python Rules Engine
  python-rules:
    build:
      context: ./python
      dockerfile: Dockerfile.rules
    container_name: fraud-detection-python-rules
    ports:
      - "5002:5001"
    networks:
      - fraud-detection-network

networks:
  fraud-detection-network:
    driver: bridge

volumes:
  mongodb_data:

